/*
 * OpenLigaDB-API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Org.OpenAPITools.Client.OpenAPIDateConverter;

namespace Org.OpenAPITools.Model
{
    /// <summary>
    /// GoalGetter
    /// </summary>
    [DataContract(Name = "GoalGetter")]
    public partial class GoalGetter : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="GoalGetter" /> class.
        /// </summary>
        /// <param name="goalGetterId">goalGetterId.</param>
        /// <param name="goalGetterName">goalGetterName.</param>
        /// <param name="goalCount">goalCount.</param>
        public GoalGetter(int goalGetterId = default(int), string goalGetterName = default(string), int goalCount = default(int))
        {
            this.GoalGetterId = goalGetterId;
            this.GoalGetterName = goalGetterName;
            this.GoalCount = goalCount;
        }

        /// <summary>
        /// Gets or Sets GoalGetterId
        /// </summary>
        [DataMember(Name = "goalGetterId", EmitDefaultValue = false)]
        public int GoalGetterId { get; set; }

        /// <summary>
        /// Gets or Sets GoalGetterName
        /// </summary>
        [DataMember(Name = "goalGetterName", EmitDefaultValue = true)]
        public string GoalGetterName { get; set; }

        /// <summary>
        /// Gets or Sets GoalCount
        /// </summary>
        [DataMember(Name = "goalCount", EmitDefaultValue = false)]
        public int GoalCount { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class GoalGetter {\n");
            sb.Append("  GoalGetterId: ").Append(GoalGetterId).Append("\n");
            sb.Append("  GoalGetterName: ").Append(GoalGetterName).Append("\n");
            sb.Append("  GoalCount: ").Append(GoalCount).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
