/*
 * OpenLigaDB-API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Org.OpenAPITools.Client.OpenAPIDateConverter;

namespace Org.OpenAPITools.Model
{
    /// <summary>
    /// Location
    /// </summary>
    [DataContract(Name = "Location")]
    public partial class Location : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="Location" /> class.
        /// </summary>
        /// <param name="locationID">locationID.</param>
        /// <param name="locationCity">locationCity.</param>
        /// <param name="locationStadium">locationStadium.</param>
        public Location(int locationID = default(int), string locationCity = default(string), string locationStadium = default(string))
        {
            this.LocationID = locationID;
            this.LocationCity = locationCity;
            this.LocationStadium = locationStadium;
        }

        /// <summary>
        /// Gets or Sets LocationID
        /// </summary>
        [DataMember(Name = "locationID", EmitDefaultValue = false)]
        public int LocationID { get; set; }

        /// <summary>
        /// Gets or Sets LocationCity
        /// </summary>
        [DataMember(Name = "locationCity", EmitDefaultValue = true)]
        public string LocationCity { get; set; }

        /// <summary>
        /// Gets or Sets LocationStadium
        /// </summary>
        [DataMember(Name = "locationStadium", EmitDefaultValue = true)]
        public string LocationStadium { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class Location {\n");
            sb.Append("  LocationID: ").Append(LocationID).Append("\n");
            sb.Append("  LocationCity: ").Append(LocationCity).Append("\n");
            sb.Append("  LocationStadium: ").Append(LocationStadium).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
