/*
 * OpenLigaDB-API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing BlTableTeam
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class BlTableTeamTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for BlTableTeam
        //private BlTableTeam instance;

        public BlTableTeamTests()
        {
            // TODO uncomment below to create an instance of BlTableTeam
            //instance = new BlTableTeam();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of BlTableTeam
        /// </summary>
        [Fact]
        public void BlTableTeamInstanceTest()
        {
            // TODO uncomment below to test "IsType" BlTableTeam
            //Assert.IsType<BlTableTeam>(instance);
        }

        /// <summary>
        /// Test the property 'TeamInfoId'
        /// </summary>
        [Fact]
        public void TeamInfoIdTest()
        {
            // TODO unit test for the property 'TeamInfoId'
        }

        /// <summary>
        /// Test the property 'TeamName'
        /// </summary>
        [Fact]
        public void TeamNameTest()
        {
            // TODO unit test for the property 'TeamName'
        }

        /// <summary>
        /// Test the property 'ShortName'
        /// </summary>
        [Fact]
        public void ShortNameTest()
        {
            // TODO unit test for the property 'ShortName'
        }

        /// <summary>
        /// Test the property 'TeamIconUrl'
        /// </summary>
        [Fact]
        public void TeamIconUrlTest()
        {
            // TODO unit test for the property 'TeamIconUrl'
        }

        /// <summary>
        /// Test the property 'Points'
        /// </summary>
        [Fact]
        public void PointsTest()
        {
            // TODO unit test for the property 'Points'
        }

        /// <summary>
        /// Test the property 'OpponentGoals'
        /// </summary>
        [Fact]
        public void OpponentGoalsTest()
        {
            // TODO unit test for the property 'OpponentGoals'
        }

        /// <summary>
        /// Test the property 'Goals'
        /// </summary>
        [Fact]
        public void GoalsTest()
        {
            // TODO unit test for the property 'Goals'
        }

        /// <summary>
        /// Test the property 'Matches'
        /// </summary>
        [Fact]
        public void MatchesTest()
        {
            // TODO unit test for the property 'Matches'
        }

        /// <summary>
        /// Test the property 'Won'
        /// </summary>
        [Fact]
        public void WonTest()
        {
            // TODO unit test for the property 'Won'
        }

        /// <summary>
        /// Test the property 'Lost'
        /// </summary>
        [Fact]
        public void LostTest()
        {
            // TODO unit test for the property 'Lost'
        }

        /// <summary>
        /// Test the property 'Draw'
        /// </summary>
        [Fact]
        public void DrawTest()
        {
            // TODO unit test for the property 'Draw'
        }

        /// <summary>
        /// Test the property 'GoalDiff'
        /// </summary>
        [Fact]
        public void GoalDiffTest()
        {
            // TODO unit test for the property 'GoalDiff'
        }
    }
}
