/*
 * OpenLigaDB-API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing GoalGetter
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class GoalGetterTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for GoalGetter
        //private GoalGetter instance;

        public GoalGetterTests()
        {
            // TODO uncomment below to create an instance of GoalGetter
            //instance = new GoalGetter();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of GoalGetter
        /// </summary>
        [Fact]
        public void GoalGetterInstanceTest()
        {
            // TODO uncomment below to test "IsType" GoalGetter
            //Assert.IsType<GoalGetter>(instance);
        }

        /// <summary>
        /// Test the property 'GoalGetterId'
        /// </summary>
        [Fact]
        public void GoalGetterIdTest()
        {
            // TODO unit test for the property 'GoalGetterId'
        }

        /// <summary>
        /// Test the property 'GoalGetterName'
        /// </summary>
        [Fact]
        public void GoalGetterNameTest()
        {
            // TODO unit test for the property 'GoalGetterName'
        }

        /// <summary>
        /// Test the property 'GoalCount'
        /// </summary>
        [Fact]
        public void GoalCountTest()
        {
            // TODO unit test for the property 'GoalCount'
        }
    }
}
