/*
 * OpenLigaDB-API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing Goal
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class GoalTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for Goal
        //private Goal instance;

        public GoalTests()
        {
            // TODO uncomment below to create an instance of Goal
            //instance = new Goal();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of Goal
        /// </summary>
        [Fact]
        public void GoalInstanceTest()
        {
            // TODO uncomment below to test "IsType" Goal
            //Assert.IsType<Goal>(instance);
        }

        /// <summary>
        /// Test the property 'GoalID'
        /// </summary>
        [Fact]
        public void GoalIDTest()
        {
            // TODO unit test for the property 'GoalID'
        }

        /// <summary>
        /// Test the property 'ScoreTeam1'
        /// </summary>
        [Fact]
        public void ScoreTeam1Test()
        {
            // TODO unit test for the property 'ScoreTeam1'
        }

        /// <summary>
        /// Test the property 'ScoreTeam2'
        /// </summary>
        [Fact]
        public void ScoreTeam2Test()
        {
            // TODO unit test for the property 'ScoreTeam2'
        }

        /// <summary>
        /// Test the property 'MatchMinute'
        /// </summary>
        [Fact]
        public void MatchMinuteTest()
        {
            // TODO unit test for the property 'MatchMinute'
        }

        /// <summary>
        /// Test the property 'GoalGetterID'
        /// </summary>
        [Fact]
        public void GoalGetterIDTest()
        {
            // TODO unit test for the property 'GoalGetterID'
        }

        /// <summary>
        /// Test the property 'GoalGetterName'
        /// </summary>
        [Fact]
        public void GoalGetterNameTest()
        {
            // TODO unit test for the property 'GoalGetterName'
        }

        /// <summary>
        /// Test the property 'IsPenalty'
        /// </summary>
        [Fact]
        public void IsPenaltyTest()
        {
            // TODO unit test for the property 'IsPenalty'
        }

        /// <summary>
        /// Test the property 'IsOwnGoal'
        /// </summary>
        [Fact]
        public void IsOwnGoalTest()
        {
            // TODO unit test for the property 'IsOwnGoal'
        }

        /// <summary>
        /// Test the property 'IsOvertime'
        /// </summary>
        [Fact]
        public void IsOvertimeTest()
        {
            // TODO unit test for the property 'IsOvertime'
        }

        /// <summary>
        /// Test the property 'Comment'
        /// </summary>
        [Fact]
        public void CommentTest()
        {
            // TODO unit test for the property 'Comment'
        }
    }
}
