/*
 * OpenLigaDB-API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing Group
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class GroupTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for Group
        //private Group instance;

        public GroupTests()
        {
            // TODO uncomment below to create an instance of Group
            //instance = new Group();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of Group
        /// </summary>
        [Fact]
        public void GroupInstanceTest()
        {
            // TODO uncomment below to test "IsType" Group
            //Assert.IsType<Group>(instance);
        }

        /// <summary>
        /// Test the property 'GroupName'
        /// </summary>
        [Fact]
        public void GroupNameTest()
        {
            // TODO unit test for the property 'GroupName'
        }

        /// <summary>
        /// Test the property 'GroupOrderID'
        /// </summary>
        [Fact]
        public void GroupOrderIDTest()
        {
            // TODO unit test for the property 'GroupOrderID'
        }

        /// <summary>
        /// Test the property 'GroupID'
        /// </summary>
        [Fact]
        public void GroupIDTest()
        {
            // TODO unit test for the property 'GroupID'
        }
    }
}
