/*
 * OpenLigaDB-API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing Location
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class LocationTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for Location
        //private Location instance;

        public LocationTests()
        {
            // TODO uncomment below to create an instance of Location
            //instance = new Location();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of Location
        /// </summary>
        [Fact]
        public void LocationInstanceTest()
        {
            // TODO uncomment below to test "IsType" Location
            //Assert.IsType<Location>(instance);
        }

        /// <summary>
        /// Test the property 'LocationID'
        /// </summary>
        [Fact]
        public void LocationIDTest()
        {
            // TODO unit test for the property 'LocationID'
        }

        /// <summary>
        /// Test the property 'LocationCity'
        /// </summary>
        [Fact]
        public void LocationCityTest()
        {
            // TODO unit test for the property 'LocationCity'
        }

        /// <summary>
        /// Test the property 'LocationStadium'
        /// </summary>
        [Fact]
        public void LocationStadiumTest()
        {
            // TODO unit test for the property 'LocationStadium'
        }
    }
}
