/*
 * OpenLigaDB-API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing Match
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class MatchTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for Match
        //private Match instance;

        public MatchTests()
        {
            // TODO uncomment below to create an instance of Match
            //instance = new Match();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of Match
        /// </summary>
        [Fact]
        public void MatchInstanceTest()
        {
            // TODO uncomment below to test "IsType" Match
            //Assert.IsType<Match>(instance);
        }

        /// <summary>
        /// Test the property 'MatchID'
        /// </summary>
        [Fact]
        public void MatchIDTest()
        {
            // TODO unit test for the property 'MatchID'
        }

        /// <summary>
        /// Test the property 'MatchDateTime'
        /// </summary>
        [Fact]
        public void MatchDateTimeTest()
        {
            // TODO unit test for the property 'MatchDateTime'
        }

        /// <summary>
        /// Test the property 'TimeZoneID'
        /// </summary>
        [Fact]
        public void TimeZoneIDTest()
        {
            // TODO unit test for the property 'TimeZoneID'
        }

        /// <summary>
        /// Test the property 'LeagueId'
        /// </summary>
        [Fact]
        public void LeagueIdTest()
        {
            // TODO unit test for the property 'LeagueId'
        }

        /// <summary>
        /// Test the property 'LeagueName'
        /// </summary>
        [Fact]
        public void LeagueNameTest()
        {
            // TODO unit test for the property 'LeagueName'
        }

        /// <summary>
        /// Test the property 'LeagueSeason'
        /// </summary>
        [Fact]
        public void LeagueSeasonTest()
        {
            // TODO unit test for the property 'LeagueSeason'
        }

        /// <summary>
        /// Test the property 'LeagueShortcut'
        /// </summary>
        [Fact]
        public void LeagueShortcutTest()
        {
            // TODO unit test for the property 'LeagueShortcut'
        }

        /// <summary>
        /// Test the property 'MatchDateTimeUTC'
        /// </summary>
        [Fact]
        public void MatchDateTimeUTCTest()
        {
            // TODO unit test for the property 'MatchDateTimeUTC'
        }

        /// <summary>
        /// Test the property 'Group'
        /// </summary>
        [Fact]
        public void GroupTest()
        {
            // TODO unit test for the property 'Group'
        }

        /// <summary>
        /// Test the property 'Team1'
        /// </summary>
        [Fact]
        public void Team1Test()
        {
            // TODO unit test for the property 'Team1'
        }

        /// <summary>
        /// Test the property 'Team2'
        /// </summary>
        [Fact]
        public void Team2Test()
        {
            // TODO unit test for the property 'Team2'
        }

        /// <summary>
        /// Test the property 'LastUpdateDateTime'
        /// </summary>
        [Fact]
        public void LastUpdateDateTimeTest()
        {
            // TODO unit test for the property 'LastUpdateDateTime'
        }

        /// <summary>
        /// Test the property 'MatchIsFinished'
        /// </summary>
        [Fact]
        public void MatchIsFinishedTest()
        {
            // TODO unit test for the property 'MatchIsFinished'
        }

        /// <summary>
        /// Test the property 'MatchResults'
        /// </summary>
        [Fact]
        public void MatchResultsTest()
        {
            // TODO unit test for the property 'MatchResults'
        }

        /// <summary>
        /// Test the property 'Goals'
        /// </summary>
        [Fact]
        public void GoalsTest()
        {
            // TODO unit test for the property 'Goals'
        }

        /// <summary>
        /// Test the property 'Location'
        /// </summary>
        [Fact]
        public void LocationTest()
        {
            // TODO unit test for the property 'Location'
        }

        /// <summary>
        /// Test the property 'NumberOfViewers'
        /// </summary>
        [Fact]
        public void NumberOfViewersTest()
        {
            // TODO unit test for the property 'NumberOfViewers'
        }
    }
}
