/*
 * OpenLigaDB-API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing MatchResult
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class MatchResultTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for MatchResult
        //private MatchResult instance;

        public MatchResultTests()
        {
            // TODO uncomment below to create an instance of MatchResult
            //instance = new MatchResult();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of MatchResult
        /// </summary>
        [Fact]
        public void MatchResultInstanceTest()
        {
            // TODO uncomment below to test "IsType" MatchResult
            //Assert.IsType<MatchResult>(instance);
        }

        /// <summary>
        /// Test the property 'ResultID'
        /// </summary>
        [Fact]
        public void ResultIDTest()
        {
            // TODO unit test for the property 'ResultID'
        }

        /// <summary>
        /// Test the property 'ResultName'
        /// </summary>
        [Fact]
        public void ResultNameTest()
        {
            // TODO unit test for the property 'ResultName'
        }

        /// <summary>
        /// Test the property 'PointsTeam1'
        /// </summary>
        [Fact]
        public void PointsTeam1Test()
        {
            // TODO unit test for the property 'PointsTeam1'
        }

        /// <summary>
        /// Test the property 'PointsTeam2'
        /// </summary>
        [Fact]
        public void PointsTeam2Test()
        {
            // TODO unit test for the property 'PointsTeam2'
        }

        /// <summary>
        /// Test the property 'ResultOrderID'
        /// </summary>
        [Fact]
        public void ResultOrderIDTest()
        {
            // TODO unit test for the property 'ResultOrderID'
        }

        /// <summary>
        /// Test the property 'ResultTypeID'
        /// </summary>
        [Fact]
        public void ResultTypeIDTest()
        {
            // TODO unit test for the property 'ResultTypeID'
        }

        /// <summary>
        /// Test the property 'ResultDescription'
        /// </summary>
        [Fact]
        public void ResultDescriptionTest()
        {
            // TODO unit test for the property 'ResultDescription'
        }
    }
}
