/*
 * OpenLigaDB-API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing Sport
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class SportTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for Sport
        //private Sport instance;

        public SportTests()
        {
            // TODO uncomment below to create an instance of Sport
            //instance = new Sport();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of Sport
        /// </summary>
        [Fact]
        public void SportInstanceTest()
        {
            // TODO uncomment below to test "IsType" Sport
            //Assert.IsType<Sport>(instance);
        }

        /// <summary>
        /// Test the property 'SportId'
        /// </summary>
        [Fact]
        public void SportIdTest()
        {
            // TODO unit test for the property 'SportId'
        }

        /// <summary>
        /// Test the property 'SportName'
        /// </summary>
        [Fact]
        public void SportNameTest()
        {
            // TODO unit test for the property 'SportName'
        }
    }
}
