/*
 * OpenLigaDB-API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing Team
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class TeamTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for Team
        //private Team instance;

        public TeamTests()
        {
            // TODO uncomment below to create an instance of Team
            //instance = new Team();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of Team
        /// </summary>
        [Fact]
        public void TeamInstanceTest()
        {
            // TODO uncomment below to test "IsType" Team
            //Assert.IsType<Team>(instance);
        }

        /// <summary>
        /// Test the property 'TeamId'
        /// </summary>
        [Fact]
        public void TeamIdTest()
        {
            // TODO unit test for the property 'TeamId'
        }

        /// <summary>
        /// Test the property 'TeamName'
        /// </summary>
        [Fact]
        public void TeamNameTest()
        {
            // TODO unit test for the property 'TeamName'
        }

        /// <summary>
        /// Test the property 'ShortName'
        /// </summary>
        [Fact]
        public void ShortNameTest()
        {
            // TODO unit test for the property 'ShortName'
        }

        /// <summary>
        /// Test the property 'TeamIconUrl'
        /// </summary>
        [Fact]
        public void TeamIconUrlTest()
        {
            // TODO unit test for the property 'TeamIconUrl'
        }

        /// <summary>
        /// Test the property 'TeamGroupName'
        /// </summary>
        [Fact]
        public void TeamGroupNameTest()
        {
            // TODO unit test for the property 'TeamGroupName'
        }
    }
}
